git:
 submodules: false

language: c

os:
 - osx
 - linux

branches:
 only:
   - master
   - /^maint.*/

before_install:
 - date -u
 - uname -a
 - env | grep -v "BINTRAY_API_KEY" | sort
 - git submodule update --init

install: true

script: ./build.libgit2.sh

after_success: ./uploadbinaries.sh
